version: "3.9"

services:
  postgres:
    container_name: chaindexing-examples
    image: "postgres:14"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: chaindexing-examples-db
    ports:
      - "5432:5432"
