[package]
name = "nfts"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
chaindexing = "0.1.40"
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }


