[package]
name = "uniswap"
edition = "2021"

[dependencies]
async-trait = "0.1"
chaindexing = { git = "https://github.com/chaindexing/chaindexing-rs", rev="ae070e2" }
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
